### ISSUE TITLE
Using plain php with yaml content doesn't work

### ISSUE THREAD

**Issue by therro** [igorw/ConfigServiceProvider#18]
The readme says you can change the file extension of your yaml file to '.php'. That's not true, because the script expects php code (line 132).

**Comment by igorw** [comment]
Yeah, I suppose the README could be reworded a bit.

If you're renaming it to .php to make it inaccessible by the webserver, then you're probably doing it wrong. In that case you'd really want to move the config files out of the webroot altogether, or if that's not possible, at least restrict access via webserver config.

**Comment by igorw** [comment]
I've improved this: 1b834386a3e535a95928445129390242fb5a7b05.
