### ISSUE TITLE
toml problem with array

### ISSUE THREAD

**Issue by fzerorubigd** [igorw/ConfigServiceProvider#21]
I use json like this : 

```
{
    "twig.path" : {
        "base" : "%root_dir%/app/views"
    }
}
```

And every thing is ok. since json compile it to this array : 

```
Array ( [twig.path] => Array ( [base] => %root_dir%/app/views ) )
```

But there is no way to get this array in toml : 

```
[twig]
    [path]
        base =  "%root_dir%/app/views"

 OR 

[twig.path]
    base = "%root_dir%/app/views"
```

All translated to 

```
Arrary ([twig] => Array ([path] => array ([base] => "%root_dir%/app/views")))
```

So merge this is not possible since twig is an object. (I already have $app['twig'] )

**Comment by igorw** [comment]
Basically, TOML is stupid. To quote the TOML spec:

> Nested hashes are denoted by key groups with dots in them. Name your key groups whatever crap you please, just don't use a dot. Dot is reserved. OBEY.

_facepalm_

I suggest not using TOML. But I cannot remove support for it without breaking BC, so I will keep it for now.
