### ISSUE TITLE
composer.json out-of-date?

### ISSUE THREAD

**Issue by StanAngeloff** [igorw/ConfigServiceProvider#23]
I just tried using the provider in a Silex 1.1.x application and Composer failed to finish an install because of conflicts. Looking at the `composer.json` file, Silex is locked at `1.0.*@dev` whereas locally I have `1.1.*@dev`.

Is there any reason why `1.1.x` is not supported in `master`?

**Comment by igorw** [comment]
The 1.1 branch is not stable yet. That said, there is no reason not to support it, so I will loosen the constraint.

**Comment by igorw** [comment]
FYI, I tagged v1.2.1 which should work on silex 1.1. Let me know if there are any problems with it.

**Comment by StanAngeloff** [comment]
Great, just installed via Composer with no warnings/errors. I agree, there shouldn't be a reason to exclude Silex 1.1 support in the `master` branch. Thanks.
