### ISSUE TITLE
Comments support for JSON configurations

### ISSUE THREAD

**Issue by dietrich-stein** [igorw/ConfigServiceProvider#25]
Very nice provider, thank you. I am still resisting the lure of YAML, but JSON is very attractive. Would you consider adding some pre-processing to your parseJson() routine in order to enable comments within JSON files? As this is a must-have for me I thought I'd ask before forking.

Someone has even worked out the regexp to clean out // and /**/ comments in a single swoop and put it in a nice wrapper already. http://www.php.net/manual/en/function.json-decode.php#111551

**Comment by igorw** [comment]
The JSON format does not have support for comments, and as such I will not support them. Any library that adds support for JSON comments breaks compatibility with the standard and also breaks interop with any other JSON tool. If you really need comments, use a format that supports them, such as yml or PHP.

**Comment by dietrich-stein** [comment]
If a user of your library creates .json files with comments in them, and then that user or a third-party attempts to decode those files using another library that does not support comments then you would be culpable of negligence; at least arguably. Your decision is based on sound logic good sir.

However, would you consider accepting a pull request to introduce a new driver that achieves JSON with comments under an alternate file extension? I would gladly name such a driver "JsoncfgConfigDriver.php" and intend it to load .jsoncfg files. I understand that sufficient precaution must be taken to avoid perpetuating bad practices against the standard. But Douglas Crockford himself has even suggested using a minifier before decoding for exactly this purpose when using JSON for configurations. The driver could simply wrap json_decode() with json_minify() which is available MIT licensed from here: https://github.com/getify/JSON.minify/blob/master/minify.json.php

**Comment by igorw** [comment]
I don't really see the point in a custom unspecified "json with comments" format. If there were a spec for it and it had adoption, then maybe I would accept a PR. But at that point you might as well use a format that _does_ have comments natively, which is what I would suggest.
