### ISSUE TITLE
Keys in config like %smth% should work as reference not force users to have actual keys

### ISSUE THREAD

**Issue by danaki** [igorw/ConfigServiceProvider#27]
If I have

``` php
[
    '%root%' => '/www/app'
]
```

I used to refer to it from the same config using %root%, example:

``` php
[
    '%root%' => '/www/app',
    'templates' => '%root%/templates'
]
```

This is ok if I need to refer to templates from my code using $app['templates'] but if I need to refer to the root I used to get it from $app['%root%'] which makes some config keys look with '%' signs, some without. To have only keys without '%' I used to override them in the same config like so:

``` php
[
    '%_root%' => '/www/app',
    'root' => '%_root%',
    'templates' => '%_root%/templates'
]
```

May be it's better to treat '%.+%' just like symbolic reference to other config keys, in this case would work:

``` php
[
    'root' => '/www/app',
    'templates' => '%root%/templates'
]
```

If your approach is just a matter of choice of design, feel free to close this ticket.

**Comment by igorw** [comment]
It would not make much sense to merge #26 without making this change also. However breaking the replacements concept would break BC, so I will not do it. It can be re-considered for a 2.0, but I'm not planning to make such a change at this point.
