### ISSUE TITLE
Multiple file parsing

### ISSUE THREAD

**Issue by J7mbo** [igorw/ConfigServiceProvider#28]
It would be so much nicer to, instead of this:

```
$this->register(new ConfigServiceProvider(
    __DIR__."/../../config/services.yml",
));

$this->register(new ConfigServiceProvider(
    __DIR__."/../../config/routes.yml",
));

$this->register(new ConfigServiceProvider(
    __DIR__."/../../config/another.yml",
));

// DRY is being hit here, 3 being the magic number and all...
```

Be able to do this:

```
$this->register(new ConfigServiceProvider(array(
    __DIR__."/../../config/services.yml",
    __DIR__."/../../config/routes.yml",
    __DIR__."/../../config/another.yml"
)));
```

Nothing major, just _much_ nicer and easier to use.

**Comment by igorw** [comment]
It would probably make the code quite a bit more unmaintainable. If you can make a PR with tests that keeps the code straight-forward I will consider it.

An alternative would be to just make your own little function for this.

**Comment by J7mbo** [comment]
I already gave it a go, then resorted to posting an issue in the hope you may have considered it before ;) Sounds like a helper is the best way forward then.

**Comment by igorw** [comment]
I guess I'll close this then. Feel free to open a PR if you have something you think is acceptable.
