### ISSUE TITLE
Seems to be a dead project, fork?

### ISSUE THREAD

**Issue by dominikzogg** [igorw/ConfigServiceProvider#43]
@igorw if i am wrong, sorry for that, answer here, and i will stop asking for a fork.

I am right, anybody of us should for this as the new ConfigServiceProvider for Silex (Silex 2.0 support, symfony 2.7 fixes...)

@BlackScorp @henrikbjorn @Seldaek @localheinz @parhamdoustdar ....

**Comment by henrikbjorn** [comment]
github.com/flint/tacker provides some of the same things and there is a serviceprovider in github.com/flint/brick that is compatible with Silex 2.0

**Comment by dominikzogg** [comment]
I forked it at: https://github.com/saxulum/ConfigServiceProvider

**Comment by Seldaek** [comment]
I talked to Igor yesterday. He says if you email him he'll grant whoever
wants to take over access to this repo. It would be better than forking IMO

**Comment by dominikzogg** [comment]
@Seldaek I wrote @igorw a mail, lets see what will happen
