### ISSUE TITLE
bool to int/string conversion when passing replacements in YAML

### ISSUE THREAD

**Issue by gremo** [igorw/ConfigServiceProvider#6]
Is this the wanted behavior?

```
# config.dev.yml

# Activate debug
debug: true

# Access-Control-Allow-Origin header for CORS
access_control_allow_origin: "*"

# Monolog configuration
monolog.logfile: %app_dir%/logs/dev.log
monolog.level: Logger::DEBUG
```

```
$replacement = array('app_dir' => __DIR__ . '/../app');

$app->register(new ConfigServiceProvider(__DIR__ . "/../app/config.$env.yml", $replacement));
```

Dumping `$app` shows `'debug' => string '1' (length=1)`, while remiving `$replacement` i get `'debug' => boolean true`. 

Setting it to `false` and you'll get an empty string `'debug' => string '' (length=0)`.

Not a big issue since `1` evaluates to `true` while empty string to `false`, but can you fix this? Thank you!

**Comment by igorw** [comment]
Thanks, fixed!
